export const ActionTypes = {    
    STORE_INITIATE:"STORE_INITIATE",
    ADD_TODO: "ADD_TODO",
    SET_FILTER: "SET_FILTER",
    // TOGGLE_TODO: "TOGGLE_TODO",
    // SHOW_ALL: 'SHOW_ALL',
    // SHOW_COMPLETED: 'SHOW_COMPLETED',
    // SHOW_ACTIVE: 'SHOW_ACTIVE'
};