export const ActionTypes = {    
    STORE_INITIATE:"STORE_INITIATE",
    SET_DATA: "SET_DATA",
    UPDATE_LIGHTBOX:"UPDATE_LIGHTBOX",
    UPDATE_DATA: "UPDATE_DATA",
    ACTION_WITHOUT_REACT_REDUX: "ACTION_WITHOUT_REACT_REDUX"
};